### ISSUE TITLE
I am getting values as blank

### ISSUE THREAD

**Issue by Naveenn14** [pavithra20august/Exploratory-Data-analysis#1]
When i ran df.head(5). I am getting blank values. i used the same code I just changed the file name. I didn't get any errors when i ran the previous codes. can you please help?

![image](https://user-images.githubusercontent.com/49560487/120110983-96d4a580-c18d-11eb-95ba-528b9dc1915a.png)

**Comment by pavithra20august** [comment]
Hi..can you check all your columns length are same.And for authors name,I wrote regex for first _name space last_name.make sure you have the same format.You need to clean your data before running this
